spring:
  datasource:
    generate-unique-name: false
    # H2 Database 配置
    name: blog
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.miniBlog/db/blog
    username: admin
    password: 123456

  jpa:
    # jpa 配置
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  thymeleaf:
    # thymeleaf配置
    cache: false
    prefix: classpath:/templates/
    suffix: .html
